dist:
  - xenial

language:
  - cpp

sudo:
  - false

os:
  - linux

addons:
  apt:
    packages:
      - wget
      - rubberband-cli
      
before_install:
  - wget https://code.soundsoftware.ac.uk/attachments/download/2250/sonic-annotator_1.5_amd64.deb
  - sudo apt install -y ./sonic-annotator_1.5_amd64.deb
  - ( cd ../ ; hg clone https://code.soundsoftware.ac.uk/hg/vamp-plugin-sdk )
  - ( cd ../ ; hg clone https://code.soundsoftware.ac.uk/hg/vamp-plugin-tester )
  - ( cd ../vamp-plugin-sdk ; ./configure --disable-programs && make && sudo make install )
  - ( cd ../vamp-plugin-tester ; ./repoint install && make )

script:
  - make -f Makefile.linux test
  - VAMP_PATH=. ../vamp-plugin-tester/vamp-plugin-tester -a
