

#CFLAGS	:= -Wall -Wextra -Werror -g -fPIC -std=c++11

CFLAGS          := -Wall -Wextra -Werror -O3 -msse -msse2 -mfpmath=sse -ftree-vectorize -fPIC
CXXFLAGS	:= -std=c++11

VAMPSDK_DIR	:= ../vamp-plugin-sdk

PLUGIN_LDFLAGS	:= -shared -Wl,-Bsymbolic -Wl,-z,defs -Wl,--version-script=vamp-plugin.map -L$(VAMPSDK_DIR) -Wl,-Bstatic -lvamp-sdk -Wl,-Bdynamic

PLUGIN_EXT	:= .so

MAKEFILE_EXT  := .linux

include Makefile.inc


